### ISSUE TITLE
Sort.py won't accept crop sizes other than 600

### ISSUE THREAD

**Issue by ChlupacTheBosmer** [ChlupacTheBosmer/ICVT#1]
Traceback (most recent call last):
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\sort.py", line 115, in <module>
    canvas[:, image_x:image_x + image_width, :] = image
ValueError: could not broadcast input array from shape (320,320,3) into shape (640,640,3)

@Bug @Feature_request

**Comment by ChlupacTheBosmer** [comment]
Changed the window size variables fed into the script to be dynamic base on the resolution of the given image.

@Jan-t2b-filip
Please check if the fix worked.

**Comment by Jan-t2b-filip** [comment]
> 
Changing the window size variables did not help.

(vid_env) C:\Users\janfi\miniconda3\envs\vid_env\ICVT>python sort.py
Traceback (most recent call last):
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\sort.py", line 107, in <module>
    image_height, image_width = image.shape
ValueError: too many values to unpack (expected 2)

**Comment by ChlupacTheBosmer** [comment]
Ok, the new commit should address this.

**Comment by Jan-t2b-filip** [comment]
Working smoothly now, thanks! (šikula)
